import { bellName, bodyName, locationName, tagName } from './content';
import type { ArchiveDocument, SaveV2 } from './types';
const esc = (value: string) => value.replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[char] ?? char);
export const reader = (doc: ArchiveDocument | undefined, state: SaveV2, revealed: boolean) => {
  if (!doc) return `<section id="reader" class="panel reader empty" tabindex="-1"><p class="eyebrow">档案阅读器</p><h2>尚未打开记录</h2><p>从查询台组合时段、地点与肉体条件，打开第一份记录。</p></section>`;
  const annotation = state.annotations[doc.id] || [];
  const segments = doc.segments.map((segment) => `<article class="segment ${segment.type}" id="${esc(segment.id)}"><div class="segment-heading">${segment.speaker ? `<span class="speaker">肉体识别：${esc(bodyName(segment.speaker))}</span>` : ''}<button class="quiet segment-quote" data-action="quote-segment" data-doc="${esc(doc.id)}" data-segment="${esc(segment.id)}">引用本段</button></div><p>${esc(segment.text)}</p><div class="tag-row">${doc.tagOptions.map((tag) => { const key = `${segment.id}:${tag}`; return `<button class="tag ${annotation.includes(key) ? 'active' : ''}" data-action="tag" data-doc="${esc(doc.id)}" data-segment="${esc(segment.id)}" data-tag="${esc(tag)}" aria-pressed="${annotation.includes(key)}">${esc(tagName(tag, revealed))}</button>`; }).join('')}</div></article>`).join('');
  return `<section id="reader" class="panel reader" tabindex="-1"><div class="archive-heading"><div><p class="eyebrow">${esc(doc.sceneId)}</p><h2>${esc(doc.title)}</h2></div><div class="reader-actions"><button class="quiet" data-action="pin-doc" data-doc="${esc(doc.id)}">${state.pinnedDocIds.includes(doc.id) ? '取消固定' : '固定档案'}</button><button class="quiet" data-action="compare-doc" data-doc="${esc(doc.id)}">纳入比较</button></div></div><dl class="metadata"><div><dt>时段</dt><dd>${esc(bellName(doc.bell))}</dd></div><div><dt>地点</dt><dd>${esc(locationName(doc.location))}</dd></div><div><dt>物理在场</dt><dd>${doc.bodies.map(bodyName).map(esc).join('、')}</dd></div><div><dt>来源／可靠性</dt><dd>${esc(doc.sources)} · ${esc(doc.reliability)}</dd></div></dl><div class="segments">${segments}</div><aside class="attachment"><h3>附件</h3>${doc.attachments.map((item) => `<p>${esc(item)}</p>`).join('')}</aside><p class="reader-note">${revealed ? '记录中的姓名按肉体识别；以下推演均由调查者自行建立。' : '本档案记录脸、声线、门禁与物品；它不解释行为为何异常。'}</p></section>`;
};
