import { bodyName, content } from './content';
import { conflictingBodies } from './hypothesis-rules';
import { deriveOccupancy } from './ring';
import type { SaveV2 } from './types';
const esc = (value: string) => value.replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[char] ?? char);
const options = (selected: string | null = null) => `<option value="">未定</option>${content.characters.map((character) => `<option value="${character.id}" ${selected === character.id ? 'selected' : ''}>${esc(character.cn)}</option>`).join('')}`;
export const hypothesesPanel = (state: SaveV2, revealed: boolean) => {
  if (!revealed) return `<section class="panel compact concealed"><h2>未解释情报</h2><p>先整理异常技能、私密情报与身体限制。正式推演工具会在取得足够原件后出现。</p></section>`;
  const activeBell = state.query.bell === 'b0' ? 'b1' : state.query.bell;
  const conflicts = conflictingBodies(state.hypotheses, activeBell);
  const grid = content.characters.map((character) => { const cell = state.hypotheses[activeBell][character.id]; return `<tr class="${conflicts.has(character.id) ? 'hypothesis-conflict' : ''}"><th scope="row">${esc(character.cn)}</th><td><select data-hyp-bell="${activeBell}" data-hyp-body="${character.id}">${options(cell.primaryCandidate)}</select></td><td><label class="check-label"><input type="checkbox" data-hyp-uncertain="${activeBell}:${character.id}" ${cell.uncertain ? 'checked' : ''}/>不确定</label></td><td><button class="quiet" data-action="use-current-evidence" data-hyp-bell="${activeBell}" data-hyp-body="${character.id}">${cell.evidenceRefs.length ? `证据 ${cell.evidenceRefs.length}` : '引用当前段'}</button></td></tr>`; }).join('');
  const ringOptions = (selected: string) => `<option value="">请选择</option>${content.characters.map((character) => `<option value="${character.id}" ${selected === character.id ? 'selected' : ''}>${esc(character.cn)}</option>`).join('')}`;
  const submitted = state.stageSubmissions.originalRing?.correct ? deriveOccupancy(state.stageSubmissions.originalRing.ring) : null;
  return `<section class="panel compact hypothesis"><h2>灵魂假设</h2><p class="small">以下是你的工作假设，不是系统确认事实。当前填写：${esc(activeBell.toUpperCase())}。${conflicts.size ? '有候选被多个肉体同时指向；这是一一对应冲突，仍由你决定是否修正。' : ''}</p><div class="table-wrap"><table class="hypothesis-grid"><thead><tr><th>肉体</th><th>主要候选</th><th>状态</th><th>证据</th></tr></thead><tbody>${grid}</tbody></table></div><fieldset class="ring-workbench"><legend>原始圆环</legend><p class="small">根据已读校样排列七人。编辑时不会判定；只在提交时检查方向。</p><div class="ring-inputs">${Array.from({ length: 7 }, (_, index) => `<label>${index + 1}<select data-ring-index="${index}">${ringOptions(state.draftOriginalRing[index] || '')}</select></label>`).join('')}</div><button data-action="submit-ring">提交圆环</button></fieldset>${submitted ? `<section class="derivation"><h3>由已提交规则推导</h3><p class="small">以下是将你提交的原始排列按原件所述方向推进所得的 B1–B4 结果，不是系统直接发现的事实。</p><div class="table-wrap"><table><thead><tr><th>肉体</th>${Object.keys(submitted).map((bell) => `<th>${bell.toUpperCase()}</th>`).join('')}</tr></thead><tbody>${content.characters.map((character) => `<tr><th>${esc(character.cn)}</th>${Object.values(submitted).map((occupancy) => `<td>${esc(bodyName((occupancy as Record<string, string>)[character.id]))}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>` : ''}</section>`;
};
