import { b7AlignmentPanel } from './b7-timeline';
import { finalExamPanel } from './final-exam';
import { bodyName, content, documents } from './content';
import { conflictingBodies } from './hypothesis-rules';
import { deriveModifiedOccupancy, liveFrameAvailable } from './modified-frame';
import { deriveOccupancy } from './ring';
import type { SaveV2, SaveV3, SaveV5 } from './types';

const esc = (value: string) => value.replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[char] ?? char);
const options = (selected: string | null = null) => `<option value="">未定</option>${content.characters.map((character) => `<option value="${character.id}" ${selected === character.id ? 'selected' : ''}>${esc(character.cn)}</option>`).join('')}`;
// 派生表证据入口：B5–B7 每列对应一份可佐证该列演算的档案，按 docId 在草稿与已提交证据中查找，避免总开第一条。
const derivedEvidenceDoc: Record<string, string> = { b5: 'doc_b4_a_mateo', b6: 'doc_b6_a_niko', b7: 'doc_b5_a_niko_mateo' };
const evidenceLabels = (state: SaveV3) => state.modifiedFrameDraft.evidenceRefs.map((ref, index) => `<li><button class="quiet" data-action="open-modified-evidence" data-evidence-index="${index}">${esc(documents.get(ref.docId)?.title || ref.docId)}${ref.segmentId ? ` · ${esc(ref.segmentId)}` : ''}</button><button class="quiet" data-action="remove-modified-evidence" data-evidence-index="${index}" aria-label="移除此条实时版框证据">×</button></li>`).join('') || '<li class="muted">尚未引用段落。</li>';
const liveFramePanel = (state: SaveV3) => {
  if (!liveFrameAvailable(state)) return '';
  const draft = state.modifiedFrameDraft;
  const sixOptions = (selected: string) => `<option value="">请选择</option>${content.characters.filter((character) => character.id !== draft.anchorBody).map((character) => `<option value="${character.id}" ${selected === character.id ? 'selected' : ''}>${esc(character.cn)}</option>`).join('')}`;
  const submitted = state.modifiedFrameSubmission?.correct && state.stageSubmissions.originalRing ? state.derivedOccupancyB5B7 ?? deriveModifiedOccupancy(state.stageSubmissions.originalRing.ring, state.modifiedFrameSubmission) : null;
  return `<section class="live-frame" aria-labelledby="live-frame-title"><div class="live-frame-heading"><p class="eyebrow">SIX-SLOT SUBTABLE</p><h2 id="live-frame-title">实时版框</h2><p class="small">这是玩家正在整理的规则假设；编辑时不判定。提交需引用至少三段、来自至少两份档案。</p></div><div class="live-fields"><label>改版发生在<select data-modified-field="changedAfterBell"><option value="">请选择</option>${content.bells.filter((bell) => bell.id !== 'b0').map((bell) => `<option value="${bell.id}" ${draft.changedAfterBell === bell.id ? 'selected' : ''}>${esc(bell.label)}</option>`).join('')}</select></label><label>改版者灵魂<select data-modified-field="modifierSoul">${options(draft.modifierSoul)}</select></label><label>被取出的姓名<select data-modified-field="removedName">${options(draft.removedName)}</select></label><label>被锚定肉体<select data-modified-field="anchorBody">${options(draft.anchorBody)}</select></label></div><fieldset class="six-ring-workbench"><legend>六槽轮转顺序</legend><p class="small">填写剩余六具肉体的顺序。整体旋转等价，反向不等价。</p><div class="ring-inputs six-ring-inputs">${Array.from({ length: 6 }, (_, index) => `<label>${index + 1}<select data-live-ring-index="${index}">${sixOptions(draft.sixBodyRing[index] || '')}</select></label>`).join('')}</div></fieldset><section class="live-evidence"><h3>提交证据 <span>${draft.evidenceRefs.length}/3</span></h3><p class="small">先在档案阅读器选中具体段落，再添加到这里。</p><button class="quiet" data-action="add-modified-evidence">引用当前选中段</button><ul>${evidenceLabels(state)}</ul></section><button class="primary live-submit" data-action="submit-modified-frame">提交实时版框</button>${submitted ? `<section class="derivation live-derivation"><h3>由已提交实时版框推导</h3><p class="small">B5–B7 仅按你提交的六槽规则演算，不填入任何终局责任判断。</p><div class="table-wrap"><table><thead><tr><th>肉体</th><th>B5</th><th>B6</th><th>B7</th></tr></thead><tbody>${content.characters.map((character) => `<tr><th>${esc(character.cn)}</th>${(['b5', 'b6', 'b7'] as const).map((bell) => `<td><button class="derived-fact" data-action="open-modified-evidence" data-evidence-doc="${derivedEvidenceDoc[bell]}" data-bell="${bell}" aria-label="打开 ${bell.toUpperCase()} ${esc(character.cn)} 的提交证据">${esc(bodyName(submitted[bell][character.id]))}</button></td>`).join('')}</tr>`).join('')}</tbody></table></div></section>` : ''}</section>`;
};
export const hypothesesPanel = (state: SaveV2, revealed: boolean) => {
  if (!revealed) return `<section class="panel compact concealed"><h2>未解释情报</h2><p>先整理异常技能、私密情报与身体限制。正式推演工具会在取得足够原件后出现。</p></section>`;
  const activeBell = state.query.bell === 'b0' ? 'b1' : state.query.bell;
  const conflicts = conflictingBodies(state.hypotheses, activeBell);
  const grid = content.characters.map((character) => { const cell = state.hypotheses[activeBell][character.id]; return `<tr class="${conflicts.has(character.id) ? 'hypothesis-conflict' : ''}"><th scope="row">${esc(character.cn)}</th><td><select data-hyp-bell="${activeBell}" data-hyp-body="${character.id}">${options(cell.primaryCandidate)}</select></td><td><label class="check-label"><input type="checkbox" data-hyp-uncertain="${activeBell}:${character.id}" ${cell.uncertain ? 'checked' : ''}/>不确定</label></td><td><button class="quiet" data-action="use-current-evidence" data-hyp-bell="${activeBell}" data-hyp-body="${character.id}">${cell.evidenceRefs.length ? `证据 ${cell.evidenceRefs.length}` : '引用当前段'}</button></td></tr>`; }).join('');
  const ringOptions = (selected: string) => `<option value="">请选择</option>${content.characters.map((character) => `<option value="${character.id}" ${selected === character.id ? 'selected' : ''}>${esc(character.cn)}</option>`).join('')}`;
  const submitted = state.stageSubmissions.originalRing?.correct ? deriveOccupancy(state.stageSubmissions.originalRing.ring) : null;
  return `<section class="panel compact hypothesis"><h2>灵魂假设</h2><p class="small">以下是你的工作假设，不是系统确认事实。当前填写：${esc(activeBell.toUpperCase())}。${conflicts.size ? '有候选被多个肉体同时指向；这是一一对应冲突，仍由你决定是否修正。' : ''}</p><div class="table-wrap"><table class="hypothesis-grid"><thead><tr><th>肉体</th><th>主要候选</th><th>状态</th><th>证据</th></tr></thead><tbody>${grid}</tbody></table></div><fieldset class="ring-workbench"><legend>原始圆环</legend><p class="small">根据已读校样排列七人。编辑时不会判定；只在提交时检查方向。</p><div class="ring-inputs">${Array.from({ length: 7 }, (_, index) => `<label>${index + 1}<select data-ring-index="${index}">${ringOptions(state.draftOriginalRing[index] || '')}</select></label>`).join('')}</div><button data-action="submit-ring">提交圆环</button></fieldset>${submitted ? `<section class="derivation"><h3>由已提交规则推导</h3><p class="small">以下是将你提交的原始排列按原件所述方向推进所得的 B1–B4 结果，不是系统直接发现的事实。</p><div class="table-wrap"><table><thead><tr><th>肉体</th>${Object.keys(submitted).map((bell) => `<th>${bell.toUpperCase()}</th>`).join('')}</tr></thead><tbody>${content.characters.map((character) => `<tr><th>${esc(character.cn)}</th>${Object.values(submitted).map((occupancy) => `<td>${esc(bodyName((occupancy as Record<string, string>)[character.id]))}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>` : ''}${liveFramePanel(state as SaveV3)}${b7AlignmentPanel(state as unknown as SaveV5)}${finalExamPanel(state as unknown as SaveV5)}</section>`;
};
